version: "3.8"
services:

  initializer:
    image: alpine
    container_name: solr-initializer
    restart: "no"
    entrypoint: |
      /bin/sh -c "chown 8983:8983 /solr"
    volumes:
      - ./data/solr:/solr

  solr:
    depends_on:
      - initializer
    image: solr:latest
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - ./data/solr:/var/solr/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_alpine_server
    ports:
      - "8080:80" # Map port 8080 on host to port 80 in container
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
